### ISSUE TITLE
OR filter logic

### ISSUE THREAD

**Issue by timseriakov** [chax-at/prisma-filter#12]
Hi folks,

I'm looking for a way to search for occurrences in different fields with `OR` logic. 
As far as I understand `.addFilter` works like `AND`. 

ex.: one UI field searches by `dealerCode`, `registrationNumber`, `shortLegalName`, `longLegalName`). 

Can you please advise how to do this if possible?

**Comment by Valerionn** [comment]
Hey,

that's not directly supported by this package. There are a few workarounds for this (but all require you to manually build the filter):

### Filter by a single field, and then manually add the `OR`
You filter by `dealerCode`, and your FE always sends the `dealerCode` filter. Then, when applying the filter, you can do something like this:
```ts
public async loadVehicles(findOptions: Prisma.VehicleFindManyArgs) {
  const multiFilterValue = findOptions.where.dealerCode;
  if(multiFilterValue != null) {
    // Remove original filter, will be replaced with an OR
    delete findOptions.where.dealerCode;
    findOptions.where.OR = [
      { dealerCode: multiFilterValue },
      { registrationNumber: multiFilterValue },
      // ...
    ];
  }

  return this.prismaService.vehicle.findMany(findOptions);
}
```


### Use virtual fields
With [virtual fields](https://github.com/chax-at/prisma-filter?tab=readme-ov-file#virtual-fields), you can add fields that will be ignored by the pipe, e.g. a `!vehicleSearch` filter. You can then directly access `filterDto.filter` which is an array of all filters, and check for field `!vehicleSearch`, and then create the OR filter manually. Note that you then have to build the filter completely manually (i.e. have to specify the prisma operations, etc.) because then the package does nothing

### Add an additional query parameter
Like virtual fields, but you just send an additional `vehicleSearch` query parameter (instead of `filter`), and then completely ignore the package and treat this parameter separately.

Overall, this is a bit outside of the package's scope - we're using it to filter data tables (in which you filter/sort specific columns), and not for a "search bar" that checks multiple data fields (like you want to). If that's the only use case you have for the package, then it would probably be easier to just implement this directly without the package (otherwise, use the workarounds described above).

**Comment by timseriakov** [comment]
Thanks for the help! We are already firmly hooked on this library and I think workarounds is what I was looking for).
