### ISSUE TITLE
Params not showing in Swagger

### ISSUE THREAD

**Issue by darr1s** [chax-at/prisma-filter#6]
Hi!

I am using `new DirectFilterPipe` as described, however, Swagger is unable to translate fields and display.

**Comment by Valerionn** [comment]
Hello,

I don't use auto generated swagger documentation myself, but I guess you have to add `@ApiProperty()` decorators to the fields as described in the NestJS documentation: https://docs.nestjs.com/openapi/types-and-parameters

To do this, you can declare the types manually instead of using the definition in the readme, like this:

```typescript
export class SingleFilter<T> implements ISingleFilter<T> {
  @IsString()
  @ApiProperty() // <- TODO add this to all types below as well
  field!: keyof T & string;

  @IsEnum(FilterOperationType)
  type!: FilterOperationType;

  @IsDefined()
  value: any;
}

export class SingleFilterOrder<T> implements ISingleOrder<T> {
  @IsString()
  field!: keyof T & string;

  @IsIn(['asc', 'desc'])
  dir!: FilterOrder;
}

export class Filter<T = any> implements IFilter<T> {
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => SingleFilter)
  @IsOptional()
  filter?: Array<SingleFilter<T>>;

  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => SingleFilterOrder)
  @IsOptional()
  order?: Array<SingleFilterOrder<T>>;

  @Type(() => Number)
  @IsInt()
  @Min(0)
  offset = 0;

  @Type(() => Number)
  @IsInt()
  @Min(1)
  @Max(500)
  limit = 100;
}
```

I don't know how well swagger works with these generic types and if those are the fields you want to have in your documentation, but you can give it a try. If it doesn't work, then please give me a link to a small repo which reproduces the problem and describe what you would like to have - then I can see if I find a solution.

**Comment by darr1s** [comment]
Thanks for this, it does work! However getting it to adhere to Tabulator style is another challenge. I will stick with FE builder for now.
